LEARN ABOUT IRIS

In [1]:
# IMPORT THE DATA (CLEAN is NOT NECESSARY)
# import load_iris from sklearn library

import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()

import seaborn as sns
%matplotlib inline

In [2]:
x = iris.data
y = iris.target
print(x)
print(y)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [3]:
#print out feature_names and target_names - both come pre-built with sklearn

feature_names = iris.feature_names
target_names = iris.target_names
print(feature_names)
print(target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [4]:
#print out type of x and y
type(x)

numpy.ndarray

In [5]:
len(x)

150

In [6]:
len(y)

150

In [7]:
# SPLIT DATA

#split the data into train and test sets (train_test_split splits array randomly into train and test sets)
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size = 0.4)

print(x_train.shape)
print(x_test.shape)

(90, 4)
(60, 4)


In [8]:
# CREATE A MODEL
# import from sklearn algorithms that create a model.  Choose 'neighbors'
from sklearn.neighbors import KNeighborsClassifier

# create the model; attempt 
knn = KNeighborsClassifier(n_neighbors = 3)  
# fit the model on the train set
knn.fit(x_train,y_train)

#create prediction for the test set
y_pred = knn.predict(x_test)

In [9]:
# TEST the OUTPUT
# check results: compare prediction for the test set with actual test set target data

from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred))


0.9833333333333333


In [10]:
# IMPROVE the MODEL
# aim for right balance between test and train sets size
# change the number of n_neighbors
# possibly, have more features
# possibly, use different model
# as an example, use another model: DecisionTreeClassifier

#from sklearn.neighbors import RadiusNeighborsClassifier
#rnc = RadiusNeighborsClassifier()

######### fit the model with train data set
#rnc.fit(x_train, y_train)

######### make prediction for the test set
#y_pred = rnc.predict(x_test)

In [11]:
# TEST the OUTPUT
print(metrics.accuracy_score(y_test, y_pred))

## Radius Neighbors Classifier gets us worse result

0.9833333333333333


In [12]:
# One more model: decision tree classifier from sklearn.tree:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
# fit the model with train data set
dtc.fit(x_train, y_train)

# make a prediction for the test data set
y_pred = dtc.predict(x_test)

In [13]:
# TEST the OUTPUT
print(metrics.accuracy_score(y_test, y_pred))

0.9833333333333333


In [14]:
# TEST the model on a new sample of data:
sample = [[3,5,4,2],[2,3,5,4]]
predictions = knn.predict(sample)
print(predictions)
predict_species = [iris.target_names[p] for p in predictions]
print("predictions: ", predict_species)
print(f"Predictions: {predict_species}")

[1 2]
predictions:  ['versicolor', 'virginica']
Predictions: ['versicolor', 'virginica']


In [15]:
# Concept of model persistence: keep using and reusing the same existing model:
# the solution is save (dump) model using joblib library, then load it when needed

from joblib import dump, load
model = dump(knn, 'mlbrain.joblib')  # this creates mlbrain.joblib file in the same foler as our notebook

# the file can be reused next time when model is needed

retreived_model = load('mlbrain.joblib')

In [16]:
# Our retrieved model can be used once again, for predictions.  Test it once again:

predictions = retreived_model.predict(sample)
predict_species = [iris.target_names[p] for p in predictions]
print(f"Predictions: {predict_species}")

# As we see, the result is the same

Predictions: ['versicolor', 'virginica']
